#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory

wclean geometricVoF
wclean libso surfaceForces
./solver/Allwclean


#------------------------------------------------------------------------------
