#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions


interfaceMethods="
isoAdvector
"
ND="30 60 90 120 150"

NNu="0.01"

MAXX="128"



for XNu in $NNu
    do
        echo "Setting number of cores to $XNu"
        sed "s/XNu/$XNu/g" constant/transportProperties.template \
        > constant/transportProperties    
                
            for XM in $MAXX
                do
                    echo "Setting grid number in X direction to $XM"
                    sed "s/XM/$XM/g" system/blockMeshDict.template \
                    > system/blockMeshDict
                        
                        for method in $interfaceMethods
                            do

                            echo "Setting interface tracking method to $method"

                            sed -e "s/INTERFACE_METHOD/$method/g" \
                            system/fvSolution.template \
                            > system/fvSolution
                            
                                for XD in $ND
                                    do
                                    echo "Setting contact angle to $XD"
                                    sed "s/XD/$XD/g" 0.orig/alpha.water.template \
                                    > 0.orig/alpha.water 
                                    restore0Dir
                                    touch foam.foam
                                    runApplication blockMesh
                                    runApplication setFields
                                    runApplication $(getApplication)


                                    methodDir="$method$XM$XD"
                                    mkdir "$method$XM$XD"
                                    cp -r 0.* 1.* 2.* 1 2 3 constant system "$method$XM$XD"
                                    mv -f  0 *.dat foam.foam log.*  proc* postPro*      "$method$XM$XD"
                                    cleanCase0
                                done
                            done
                done
    done

#------------------------------------------------------------------------------
