#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions


interfaceMethods="
isoAdvector
MULES
"

MAXX="150 175 200 225 250"

NC="16"

for XN in $NC
    do
        echo "Setting number of cores to $XN"
        sed "s/XN/$XN/g" system/decomposeParDict.template \
        > system/decomposeParDict
        
        for XM in $MAXX
            do
                echo "Setting grid number in X direction to $XM"
                sed "s/XM/$XM/g" system/blockMeshDict.template \
                > system/blockMeshDict
                
                for method in $interfaceMethods
                    do

                        echo "Setting interface tracking method to $method"

                        sed -e "s/INTERFACE_METHOD/$method/g" \
                        system/fvSolution.template \
                        > system/fvSolution
                        
                        restore0Dir
                        touch foam.foam
                        runApplication blockMesh
                        runApplication setFields
                        runApplication decomposePar
                        runParallel $(getApplication)
                        runApplication reconstructPar



                        
  
                        methodDir="$method$XM"
                        mkdir "$method$XM"
                        cpfoam.foam Allrun2 "$method$XM"
                        mv -f  *.dat  postProcessing  "$method$XM"
                        
                        cp -r 0 1 system constant $method$XM
                        
                        cleanCase0
                        done
            done
    done


------------------------------------------------------------------------------
