#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions.
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions


interfaceMethods="
isoAdvector
MULES
"

# MAXX="10 20 30 40 50 60 80 90 100 120 150 180 25 75 125 175"
MAXX="50 100"

        
        for XM in $MAXX
            do
                echo "Setting grid number in X direction to $XM"
                sed "s/XM/$XM/g" system/blockMeshDict.template \
                > system/blockMeshDict
                
                for method in $interfaceMethods
                    do

                        echo "Setting interface tracking method to $method"

                        sed -e "s/INTERFACE_METHOD/$method/g" \
                        system/fvSolution.template \
                        > system/fvSolution

                        restore0Dir
                        touch foam.foam
                        runApplication blockMesh
                        runApplication setFields
                        runApplication $(getApplication)
            


                        methodDir="$method$XM"
                        mkdir "$method$XM"
                        mv -f  *.dat postProcessing  "$method$XM"
                        cleanCase0
                        done
            done


#------------------------------------------------------------------------------
