#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------
wmake $targetType thermalIncompressibleTwoPhaseMixture
wmake $targetType thermalPhaseChangeTwoPhaseMixtures
# wmake $targetType psiTwoPhaseProperties
wmake $targetType interfacePropertiesLS 

wmake $targetType

#------------------------------------------------------------------------------
